### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by foxpcteam** [neelakansha85/site-setup-wizard#1]
Hi,
no matter what email i put i always get error:
"There was an issue checking availability of email address, please try again."

also your plugin give error like:
Warning: Invalid argument supplied for foreach() in wp-content/plugins/nsd-site-setup-wizard-1.2/ssw.php on line 326

also i get:
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /wp-content/plugins/nsd-site-setup-wizard-1.2/ssw.php:326) in wp-content/plugins/pro-sites/pro-sites-files/lib/ProSites/Helper/Session.php on line 29

and
The plugin generated 184 characters of unexpected output during activation. "headers already sent"

**Comment by neelakansha85** [comment]
Hi foxpcteam,

The first error related to checking email address looks like the javascript function is not being called properly, would you mind confirming if you see the javascript file loads properly using developer tools?

For your warning related to invalid argument supplied for foreach() it seems that the plugin is trying to find information from WPMU Pretty Plugins since the configuration is set to true for using it for features page by default and you do not seem to have it installed/activated in your wordpress system. 

I am currently working on getting a simplified way of changing/configuring Site Setup Wizard options but it might take some time. So for now, I would recommend that you modify the option by changing the values of [external plugins](https://github.com/neelakansha85/nsd-site-setup-wizard/blob/master/admin/ssw_add_options.php#L106-L110) to false if you do not have them installed in system and then try to deactivate and activate plugin again. It should change the default config options.

Your session_start() error seems to be related to the same config issue and may be fixed with the config option. 

The headers already sent error might require additional information for me to check as to what is causing that. Can you please verify if you have a database entry for "ssw_config_options_nsd" in the wp_sitemeta table?
