### ISSUE TITLE
can't find a file

### ISSUE THREAD

**Issue by medrockstar** [neelakansha85/site-setup-wizard#13]
Hi,

I can't find nsd-site-setup-wizard/admin/ssw_update_options.php

Tks,

**Comment by neelakansha85** [comment]
Hi Medrockstar,

This file was removed during an update to v1.2.3. Please download the latest version [1.2.5](https://github.com/neelakansha85/nsd-site-setup-wizard/releases/tag/1.2.5) and you should be able to view the options.

For now the options are read only since the form doesn't update those options. I am working towards resolving it and hopefully should be resolved in v1.2.6 in next few days. 

However, if you want to update these options, you can modify them in [ssw_default_options.php](https://github.com/neelakansha85/nsd-site-setup-wizard/blob/1.2.5/admin/ssw_default_options.php) and simply deactivate and activate the plugin again. This will set your options for the plugin. 

Please let me know if you still have any difficulties using the plugin.

Best,
Neel
